#!/bin/bash

rm gRASPA.so *.x

#PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/compilers/bin:$PATH; export PATH
export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.5/compilers/bin:$PATH

# Comment only the last occurrence of #include in the file
sed -i -e ':a' -e '$!{N;ba' -e '}' -e 's/\(.*\)#include/\1\/\/ #include/' main.cpp

PYBIND_INCL_DIR=-I/home/z/anaconda3/lib/python3.12/site-packages/pybind11/include/
PYTHON_INCL_DIR=-I/home/z/anaconda3/include/python3.12
PYTHON_LIB_DIRS=-L/home/z/anaconda3/lib/

CXX="nvc++"

LINKFLAG="-L/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/lib64 -L/usr/lib64/ -L/opt/local/lib/gcc11/"

NVCFLAG="-O3 -std=c++20 -target=gpu -Minline -fopenmp -cuda -stdpar=multicore"

$CXX $NVCFLAG $LINKFLAG -c axpy.cu ; echo "Finished axpy.cu"

$CXX $NVCFLAG $LINKFLAG -c main.cpp ; echo "Finished main.cpp"

$CXX $NVCFLAG $LINKFLAG -c read_data.cpp ; echo "Finished read_data.cpp"

$CXX $NVCFLAG $LINKFLAG -c data_struct.cpp ; echo "Finished data_struct.cpp"

$CXX $NVCFLAG $LINKFLAG -c VDW_Coulomb.cu ; echo "Finished VDW_Coulomb.cu"

$CXX $NVCFLAG $LINKFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x ; echo "Finished Linking"

#$CXX $NVCFLAG $LINKFLAG $PYBIND_INCL_DIR  $PYTHON_INCL_DIR  $PYTHON_LIB_DIRS  -shared main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x

rm *.o
